; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Project: ESP32S3 Tech Test
; Description: Sandbox for testing new concepts and abstract modules
; Parent Architecture: Robot v0

[platformio]
src_dir = src

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
; Sustitución del Core de Arduino por versión con Bluepad32 nativo
platform_packages =
    framework-arduinoespressif32 @ https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip
    toolchain-xtensa-esp32s3 @ 12.2.0+20230208
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
framework = arduino
; board_build.partitions = partitions_singleapp_large.csv
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
	bodmer/TFT_eSPI
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson
    ; WiFi is a component in mixed mode, usually auto-detected or part of arduino core

lib_ignore = ESPAsyncTCP

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1
    -D USER_SETUP_LOADED=1
    ; --- TFT Display Configuration (ILI9341) ---
    -D ILI9341_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=48
    -D TFT_DC=47
    -D TFT_RST=21
    -D TFT_MISO=13
    -D USE_HSPI_PORT=1
    ; --- Fonts ---
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    ; --- Memory Management (PSRAM) ---
    ; -D BOARD_HAS_PSRAM
    ; -mfix-esp32-psram-cache-issue
    ; --- Memory Management (PSRAM) ---
    ; -D BOARD_HAS_PSRAM
    ; -mfix-esp32-psram-cache-issue
